# docker-compose.yml

---
networks:
  traefik_default:
    external: true
  default:
services:

  app:
    build:
      context: ./
    develop:
      watch:
        - action: rebuild
          path: app/
    environment:
      BASE_URL: ${BASE_URL:-localhost}
      BOT_TOKEN: ${BOT_TOKEN:-YOUR_BOT_TOKEN}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-""}
      DOWNLOAD_ALLOWED_DOMAINS: ${DOWNLOAD_ALLOWED_DOMAINS:-}
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "1m"
    volumes:
      - cache:/tmp/url-fairy-bot-cache/
    ports:
      - "8000:8000"
    networks:
      - default

  nginx:
    image: nginx:stable-alpine-slim
    environment:
      BASE_URL: ${BASE_URL:-localhost}
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.docker.network: traefik_default
      traefik.enable: true
      traefik.http.routers.url-fairy-bot.entrypoints: websecure
      traefik.http.routers.url-fairy-bot.rule: Host(`${BASE_URL:-localhost}`)
      traefik.http.routers.url-fairy-bot.service: url-fairy-bot
      traefik.http.routers.url-fairy-bot.tls: true
      traefik.http.routers.url-fairy-bot.tls.certresolver: ${LETSENCRYPT_RESOLVER_NAME:-letsencrypt-cloudflare-dns-challenge}
      traefik.http.services.url-fairy-bot.loadbalancer.server.port: 80
    ports:
      - ${PUBLIC_PORT:-"80:80"}
    logging:
      driver: none
    networks:
      - traefik_default
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/theme/:/theme/:ro
      - cache:/tmp/url-fairy-bot-cache/:ro

  cron:
    image: busybox:stable
    environment:
      - FILE_TTL=${FILE_TTL:-3} #days
    volumes:
      - cache:/tmp/url-fairy-bot-cache/
    command: sh -c "find /tmp/url-fairy-bot-cache/ -type f -${FILE_TTL_TYPE:-mtime} +${FILE_TTL:-3} -delete > /dev/null; find /tmp/url-fairy-bot-cache// -type d -empty -delete > /dev/null; sleep 60m"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    logging:
      driver: none

  # cobalt-api:
  #   image: ghcr.io/imputnet/cobalt:10
  #   restart: unless-stopped
  #   labels:
  #     com.centurylinklabs.watchtower.enable: "true"
  #   networks:
  #     - default
  #   environment:
  #     API_URL: cobalt-api

volumes:
  cache:
